name: Weekend Scraper

on:
  schedule:
    # Run every Saturday and Sunday at 8 PM Sydney time (10 AM UTC)
    - cron: '0 10 * * 6,0'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install chromium
      
      - name: Generate Prisma Client
        run: npx prisma generate
      
      - name: Run scraper
        run: |
          curl -X POST ${{ secrets.API_URL }}/api/scrape \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            -d '{"source": "all"}'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Send notification on failure
        if: failure()
        run: |
          echo "Scraper failed! Check the logs for details."
          # Add notification service integration here (e.g., Slack, email)